### ISSUE TITLE
Improve URI templating

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-sdk-py#102]
My initial URI templating was sloppy and has set a bad precedent. We can avoid unnecessary string operations and have clearer code by doing 

```python
URITemplate('{baseuri}/{dataset}/{query}.json').expand(
            baseuri=self.baseuri, dataset=self.name, query=address)
```

instead of 

```python
URITemplate('%s/{dataset}/{query}.json' % self.baseuri).expand(
            dataset=self.name, query=address)
```

**Comment by sgillies** [comment]
Punt.

**Comment by perrygeo** [comment]
The challenge here is that `URITemplate` escapes the input so you get `https%3A%2F%2F`instead of `https://`. I don't see any provision for specifying the protocol separately so, as long as we're using `uritemplate`, we'll have to stick with this combination of string ops and templating.
