### ISSUE TITLE
placeholder option NOT working

### ISSUE THREAD

**Issue by yuens1002** [mapbox/mapbox-sdk-py#113]
hi there, i'm not sure if this is just in my dev env or if it can be duplicated.  the placeholder option doesnt seem to work.  the following is what i have in my code block, but the 'search' string in the search box remains after refresh.

    map.addControl(new mapboxgl.Geocoder({position: 'top-left', placeholder: 'whatever string'}));

**Comment by tmcw** [comment]
Hi @yuens1002, this is the repository for our Python SDK. You're looking for https://github.com/mapbox/mapbox-gl-geocoder
