### ISSUE TITLE
Updated tileset name not found in layer, but original name is.

### ISSUE THREAD

**Issue by gonesurfing** [mapbox/mapbox-sdk-py#122]
This is very strange and may be a server side issue. Unsure of where else to post this.

I have an application where several times a day, I need to upload updated geojson data. I'd really like to be able to reuse the tileset name but overwrite the old data entirely (since I can't delete except in map box studio, which would be very cumbersome). If I upload data with the same name (or no name), the old timestamps remain which is a problem for querying the dataset.  If I reuse the tileset but supply a new name, the old timestamps are gone and the studio tile shows the new name. However, my map then gives me "Error: Source layer "test2" does not exist on source "hsig_dir" as specified by style layer "dir" — style.js:103". Surprisingly, if I supply the first name "test1" as a source-layer, my map appears to work. If I use the web "replace tileset" option and give it a different filename, the name is updated and all is good. However, this needs to be automated and work in python.

I suspect somewhere, there are some data tags that aren't being updated.  "service.list().json()" shows that the name = u'test3' on the upload which makes me think it's on the server.

The same behavior occurs with the CLI client supplying --name test2. 

Any help would be appreciated. I've been stalled on this issue for quite a while.

**Comment by perrygeo** [comment]
@gonesurfing Replication of the updates across data centers takes a little time so you might be seeing inconsistencies if you query the service immediately after posting new data. Can you check to see if waiting a minute or two after upload resolves these issue?

**Comment by gonesurfing** [comment]
I was seeing the error as much as 30 minutes after the upload.  Using the editor on mapbox studio,  the name change would appear within a minute when adding a layer.

**Comment by perrygeo** [comment]
Here's what I was able to demonstrate in a quick test:

```
#!/usr/bin/env python
import time

from mapbox import Uploader
service = Uploader()

geojson = "./data.geojson"
name = "testname01"
mapid = "testtileset01"


with open(geojson, 'r') as src:
    upload_resp = service.upload(src, tileset=mapid, name=name)
    print(upload_resp.status_code)

print(service.list().json())
```

1. Run it once, I see that
    - status code 201, ok
    - `list().json()` shows one upload
    - Studio shows one tileset with the name "testname01".
2. Run it again a few minutes later with the same name and tileset, I see that
    - status code 201, ok
    - `list().json()` shows two uploads, both with the same name and tileset. One is complete, the other is in progress.
    - Studio still shows one tileset with the name "testname01"
3. Run it again a few minutes later with a *different name*, same tileset. I see
    - status code 201, ok
    - `list().json()` shows three uploads, all with the same tileset. Two are complete, the other is in progress.
    - Studio still shows one tileset renamed to "testname02"

This is all expected behavior. I think the key point is that the upload service listing does not list tilesets - it's a record of your uploads themselves. This is described best in the [API docs](https://www.mapbox.com/api-documentation/#remove-an-upload) but it is not as clear as it could be. Currently there is no API for querying/deleting/changing a tileset directly AFAIK.

@gonesurfing I'm a little confused about the exact code you're running and what the expected behavior is. Are you seeing something different than above?

**Comment by gonesurfing** [comment]
This is what I'm seeing and is expected behavior. However when i use addLayer in my map,  I'll get an error that sourcelayer "testname02" does not exist on source "testtileset01". Meanwhile in mapbox editor,  the name clearly has been updated to "testname02" and gives no errors.

**Comment by perrygeo** [comment]
Interesting - that might be a Studio-related behavior that we're seeing. Unfortunately that's outside of my direct skills to debug. I don't think there's anything we can do about it on the python SDK side so I'm closing this ticket. Could you send an inquiry to Technical support at https://www.mapbox.com/contact/  - reference this ticket and we'll work on getting things figured out for you. Thanks @gonesurfing

**Comment by gonesurfing** [comment]
I figured it out finally. For anyone else wondering, hitting reload (or ctl-r, or f5, or whatever) doesn't refresh the tile cache until some time criteria is met (not sure what yet). Clearing the browser's cache forces a reload and the data shows up where is should.
