### ISSUE TITLE
Static API

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-sdk-py#123]
https://www.mapbox.com/api-documentation/#static

**Comment by perrygeo** [comment]
Also need to think about how we support the classic API: https://www.mapbox.com/api-documentation/#static-classic

Technically the new static API is part of the Styles API, though the docs make enough distinction between them that I'm comfortable treating it as a separate endpoint.

**Comment by andrewharvey** [comment]
Same issue over at https://github.com/mapbox/mapbox-sdk-js/issues/139.

What I'm proposing over there is what 1ec5 suggested, to replace the static api method to use the new api and rename the existing one to classic.

**Comment by lyzidiamond** [comment]
We just moved the classic static docs off the main api-documentation -- i think it's okay to de-emphasize that API in favor of the new one.
