### ISSUE TITLE
geojson returning 422 from Static

### ISSUE THREAD

**Issue by pwt-nf** [mapbox/mapbox-sdk-py#132]
hi, 

I have a `shapely` polygon object that I'm trying to pass via the SDK to return a satellite map with the geojson overlaid. The conversion process seems like it should be simple but I am getting a 422 error from the server. The shapely object looks like this:
```
In [115]: mapping(poly)
Out[115]: 
{'coordinates': (((-84.24220279669707, 37.52527225651498),
   (-84.24220337790996, 37.52524054445193),
   (-84.2422078590632, 37.52520903046366),
   (-84.24221619699594, 37.5251780180469),
   (-84.24222831140473, 37.52514780586762),
   (-84.24224408561695, 37.52511868488464),
   (-84.24226336771473, 37.52509093554767),
   (-84.24228597199803, 37.52506482509653),
   (-84.24231168077321, 37.525040604987346),
   (-84.24234024644963, 37.52501850847112),
   (-84.24237139392406, 37.52499874834746),
   (-84.2424048232301, 37.524981514915176),
   (-84.24244021242704, 37.52496697413981),
   (-84.2424772207002, 37.52495526605519),
   (-84.24251549164305, 37.524946503415116),
   (-84.24255465668956, 37.524940770607344),
   (-84.24259433866345, 37.52493812284105),
   (-84.24263415541044, 37.524938585615125),
   (-84.24267372347848, 37.5249421544726),
   (-84.24271266181026, 37.52494879504366),
   (-84.24275059541307, 37.52495844337657),
   (-84.24278715896975, 37.52497100655353),
   (-84.24282200035687, 37.52498636358555),
   (-84.24285478403571, 37.52500436657755),
   (-84.24288519428355, 37.525024842152625),
   (-84.24291293823418, 37.52504759312165),
   (-84.24293774869834, 37.525072400382335),
   (-84.24295938673687, 37.525099025029164),
   (-84.24297764396188, 37.52512721065407),
   (-84.24299234454368, 37.52515668581582),
   (-84.2430033469042, 37.525187166654014),
   (-84.24301054508068, 37.52521835962275),
   (-84.2430138697462, 37.52524996431755),
   (-84.24301328887762, 37.52528167636853),
   (-84.24300880806402, 37.52531319037145),
   (-84.2430004704532, 37.52534420282905),
   (-84.2429883563363, 37.52537441507379),
   (-84.24297258237468, 37.52540353614432),
   (-84.24295330047657, 37.52543128558752),
   (-84.24293069633435, 37.52545739615961),
   (-84.24290498763622, 37.52548161639971),
   (-84.2428764219699, 37.5255037130518),
   (-84.24284527443821, 37.52552347331109),
   (-84.24281184500974, 37.52554070687352),
   (-84.24277645562991, 37.52555524776861),
   (-84.24273944712046, 37.525566955957835),
   (-84.24270117589694, 37.52557571868344),
   (-84.24266201053621, 37.52558145155437),
   (-84.2426223282266, 37.52558409935903),
   (-84.24258251113532, 37.52558363659703),
   (-84.24254294272765, 37.52558006772489),
   (-84.24250400407391, 37.52557342711299),
   (-84.24246607017922, 37.525563778714634),
   (-84.24242950637196, 37.52555121545012),
   (-84.24239466478517, 37.52553585831183),
   (-84.24236188096525, 37.5255178551989),
   (-84.24233147064035, 37.52549737949293),
   (-84.24230372667962, 37.52547462838801),
   (-84.24227891627272, 37.5254498209917),
   (-84.24225727835662, 37.52542319621473),
   (-84.2422390213145, 37.525395010470135),
   (-84.24222432096903, 37.52536553520375),
   (-84.24221331888916, 37.52533505428001),
   (-84.2422061210269, 37.52530386124814),
   (-84.24220279669707, 37.52527225651498)),),
 'type': 'Polygon'}
```

Following instructions from the [documentation](https://github.com/mapbox/mapbox-sdk-py/blob/master/docs/static.md#static-maps) I have tried passing the object to the API as above:

`resp = service.image('mapbox.satellite', features = mapping(poly))`

and as a geojson object:

```
geo = geojson.loads(geojson.dumps(poly))
resp = service.image('mapbox.satellite', features = geo)
```
both strategies result in a status code of  `422`.

Whats the best way to create digestible geojson for use in this sdk from shapely (or other) python geo objects? Suspect @sgillies may know...

Thanks!

**Comment by sgillies** [comment]
@pwt-nf the features parameter of `service.image()` should be a sequence of features. Can you try `resp = service.image('mapbox.satellite', features = [mapping(poly)])`?

**Comment by perrygeo** [comment]
Hi Peter,

Looks like you've got a valid GeoJSON geometry but the `features` keyword argument expects a list of GeoJSON features. (@sgillies a list of geometries doesn't currently work though arguably it should) Something like this should do the trick:

```
>>> feature = {'type': 'Feature', 'properties': {}, 'geometry': mapping(geom)}
>>> res = s.image('mapbox.satellite', features=[feature])
```


@pwt-nf

**Comment by pwt-nf** [comment]
I tried the list thing with the same result. Will try @perrygeo suggestion.

Thanks!

On Oct 10, 2016 1:16 PM, Sean Gillies <notifications@github.com> wrote:

@pwt-nf<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pwt-2Dnf&d=DQMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=j3vrwyB_XzA1ItrHU6OBJeNY7D44AKrpS3wnudWzRFQ&m=8xhYbCtmPOIi_-amfWashmEuBfGnNRIVXZyKpTCyW-I&s=F7oXhIQJeZDseDDa5QwmeI_qXta5AVYvFt4MgDMgCCI&e=> the features parameter of service.image() should be a sequence of features. Can you try resp = service.image('mapbox.satellite', features = [mapping(poly)])?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mapbox_mapbox-2Dsdk-2Dpy_issues_132-23issuecomment-2D252734320&d=DQMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=j3vrwyB_XzA1ItrHU6OBJeNY7D44AKrpS3wnudWzRFQ&m=8xhYbCtmPOIi_-amfWashmEuBfGnNRIVXZyKpTCyW-I&s=aDqU4CL0Je5BBdiRHlLMjoxc_rVhTEs7ksMPeDGfocM&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AS3uDY8-5FK2YY9Splc54nRldRFEpLVqwHks5qyp0YgaJpZM4KS6b7&d=DQMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=j3vrwyB_XzA1ItrHU6OBJeNY7D44AKrpS3wnudWzRFQ&m=8xhYbCtmPOIi_-amfWashmEuBfGnNRIVXZyKpTCyW-I&s=o9ZPMM62X8b6Emh1KSuGAUYrW9b-4ABZf8NFfSHfg6A&e=>.




________________________________

This email has been scanned for spam and viruses by Proofpoint Essentials. Click here<https://us1.proofpointessentials.com/index01.php?mod_id=11&mod_option=logitem&mail_id=VjpGP17mHVpk&r_address=ptittmann%40newforests-us.com&report=1> to report this email as spam.

**Comment by pwt-nf** [comment]
@sgillies @perrygeo solution worked. seems a bit cumbersome, but thank you for the quick response!
