### ISSUE TITLE
Accept bare geometries as static map overlays

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-sdk-py#134]
Where "bare" means not in the context of a Feature. See #132 for background.

**Comment by perrygeo** [comment]
The SDK only accepts a FeatureCollection (unfortunate given its tight character limit) so we could handle it in the SDK by wrapping any GeoJSON-like object or sequence thereof in a valid FeatureCollection. A `normalize_geojson_to_featurecollection` function might be generally useful outside of this SDK.
