### ISSUE TITLE
Best approach to estimate coordTimes in Matched points

### ISSUE THREAD

**Issue by emakarov** [mapbox/mapbox-sdk-py#141]
Hi

I'm testing Map Matching API, and I send requests with coordTimes.
My question is, could you give recommendation on best way to estimate coordTimes in matched points?

**Comment by TheMarex** [comment]
@emakarov to clarify do you want the coordTimes at every input location or do you want this interpolated along the route? The latter is currently not that easy to do with our current API version.

**Comment by emakarov** [comment]
@TheMarex hi
I have finally achieved interpolated using your data in properties (indices and coordTimes)
surprisingly, not hard
if interested, can check here the idea:
https://github.com/emakarov/sgerp/blob/master/djsgerp/views.py#L138
