### ISSUE TITLE
Add Datasets API

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-sdk-py#15]
The Data API isn't on https://www.mapbox.com/developers/api/ but let's get it in the module at preview time.

**Comment by sgillies** [comment]
Status: ongoing work at #27. It works, but some details are unsettled, namely:

- The datasets API has multiple HTTP endpoints. Do we map them onto one SDK class or do we surface the endpoints as their own classes (Feature, Dataset, etc).
- There's a similar issue for the CLI: do we stick with one level of subcommand like `mbx retrieve_features` or do we go to level 2 like `mbx features retrieve`?

**Comment by jacquestardie** [comment]
In light of https://github.com/mapbox/satellite/issues/1061 and a discussion with @rclark, this would be fantastic to have.

:+1:
