### ISSUE TITLE
Key Error on credentials

### ISSUE THREAD

**Issue by drewbo** [mapbox/mapbox-sdk-py#155]
Seeing the following error when uploading:

```python
File "/usr/local/lib/python2.7/dist-packages/mapbox/services/uploads.py", line 157, in upload
url = self.stage(fileobj)
File "/usr/local/lib/python2.7/dist-packages/mapbox/services/uploads.py", line 62, in stage
aws_access_key_id=creds['accessKeyId'],
KeyError: 'accessKeyId'
```

This is possibly due to rate limiting (we're hitting the upload endpoint pretty hard at times and maybe the temp credentials endpoint is giving a 429 or something) and I'll also note that we're using v0.8.0 of the sdk (but I didn't see any changes since then that I thought would have ameliorated this)

**Comment by perrygeo** [comment]
@drewbo the `0.11.0` release has [some changes](https://github.com/mapbox/mapbox-sdk-py/blob/master/CHANGES#L3) related to upload credentials. Can you upgrade and see if the error persists?

**Comment by drewbo** [comment]
Thanks @perrygeo, I'm going to upgrade on our next deployment but since the problem doesn't always crop up, I decided to delve a little deeper. It looks like rate limiting is the issue. The [`_get_credentials`](https://github.com/mapbox/mapbox-sdk-py/blob/e3ae3e00ed3368f0529da5158c9a38bad368884a/mapbox/services/uploads.py#L32) method doesn't throw when receiving the `429` response which only has one key (`message`) and thus throws the `KeyError` above. I threw together a [quick PR to address](https://github.com/mapbox/mapbox-sdk-py/pull/157) but let me know if you have other suggestions
