### ISSUE TITLE
Drop support for Python 2.6?

### ISSUE THREAD

**Issue by cclauss** [mapbox/mapbox-sdk-py#166]
See https://travis-ci.org/mapbox/mapbox-sdk-py/jobs/210108428#L163 ... _DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6_

Python 2.6 End of Life was in 2013... https://docs.python.org/devguide/index.html#branchstatus

Should mapbox-sdk-py drop support for Python 2.6?

**Comment by sgillies** [comment]
I agree @cclauss. I removed 2.6 from the testing matrix in a commit just a few minutes ago.
