### ISSUE TITLE
Avoid concurrent uploads doctests

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-sdk-py#167]
We're running the doctests for only one of the pythons in our matrix (2.7) and this helps. If we can ensure that only a single Travis build is running the upload doctest we'll experience fewer spurious failures while we work on a well-documented upload/fail/retry workflow.

Currently we do builds for both commits and PRs. Maybe Travis surfaces the kind of build in the environment and will let us exclude one. Commits with insufficient time in between would remain a problem.

**Comment by perrygeo** [comment]
There are some [new travis settings](https://travis-ci.org/mapbox/mapbox-sdk-py/settings) which might do the trick.
![screen shot 2017-05-08 at 8 08 21 am](https://cloud.githubusercontent.com/assets/1151287/25807900/9c8cfa36-33c5-11e7-96a1-8f12eadd6973.jpg)

If we limit concurrent jobs and only build PRs (not branches) that should guarantee that we're not running concurrent doctests in CI.

**Comment by sgillies** [comment]
Done!

<img width="716" alt="untitled" src="https://cloud.githubusercontent.com/assets/33697/25808152/7baab21a-3409-11e7-864d-fbe35dc328fb.png">
