### ISSUE TITLE
0.1 release plan

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-sdk-py#17]
We can have a first release with geocoding only, but the CLI's name conflict with another `mapbox` needs to be resolved.

**Comment by sbma44** [comment]
Renaming our internal tool is probably not a realistic option. Can we detect whether `mapbox` is in the path at install time and rename to `mapbox-python` (or similar)?

**Comment by sgillies** [comment]
No, let's have a single name on every system. Easier to talk about, Google for.

maþox has a nice Gothic feel but a little challenging for some shells, I suspect :)

I see Rackspace has a new CLI named rack. The only good thing about this is that it's short, but maybe there's a good contraction or abbreviation or pun on mapbox... box? carton?

**Comment by sbma44** [comment]
`mbx` feels fine to me, and thinking about it more, it's not actually desirable to have identically-named executables across SDKs.

**Comment by sgillies** [comment]
All 0.1 milestone issues closed. After I update the readme, I'll make a PyPI release.

- [ ] readme updates
- [ ] tag
- [ ] build, upload sdist/wheels

**Comment by sbma44** [comment]
:tada: nice work

**Comment by sgillies** [comment]
Got these distributions building from Travis: https://pypi.python.org/pypi/mapbox/0.1a3. 0.1.0 here we come.

**Comment by sgillies** [comment]
https://pypi.python.org/pypi/mapbox/0.1.0.
