### ISSUE TITLE
Isn't `forward()` supporting the language query?

### ISSUE THREAD

**Issue by radscheit** [mapbox/mapbox-sdk-py#177]
In `https://github.com/mapbox/mapbox-sdk-py/blob/master/mapbox/services/geocoding.py` ' s current definition, language queries - according to `https://www.mapbox.com/api-documentation/?language=Python#geocoding` are not supported. Am I right, or did I something wrong?

**Comment by perrygeo** [comment]
Thanks @radscheit - the `language` parameter is not yet supported in the SDK but it will be quick to add. I've marked this as a target for the next release.

**Comment by radscheit** [comment]
Thanks @perrygeo
