### ISSUE TITLE
Retina with Static Api? 

### ISSUE THREAD

**Issue by FlorianBurgevin** [mapbox/mapbox-sdk-py#187]
Hello, it seems I can't choose the retina format for my static generated maps.

If I look in the code:

` if auto:
pth = '/{mapid}/geojson({overlay})/auto/{width}x{height}.{fmt}'`

But if I look at the global documentation, the url scheme is `{width}x{height}@2x.{fmt}`

So the is not the possibility to add retina images here?

**Comment by sgillies** [comment]
@FlorianBurgevin thanks for the report!
