### ISSUE TITLE
Uploads tileset with name = uuid

### ISSUE THREAD

**Issue by bravecow** [mapbox/mapbox-sdk-py#204]
```
with open('points.mbtiles', 'rb') as src:
    name = "points-{0}".format(uuid.uuid4().hex)
    print(name)
    upload_response = service.upload(src, name)

print(upload_response.json())
```

output:

```
points-872899cb2a7f49b883b3998fba0d115a
{'message': 'Invalid "tileset" value'}
```

But (with shorter name):
```
with open('points.mbtiles', 'rb') as src:
    name = "points-{0}".format(uuid.uuid4().hex)
    print(name)
    upload_response = service.upload(src, 'points-872899cb2')

print(upload_response.json())
```

Works:
```
points-e05ef96d223e41d0a58aa28ecd8c2016
{'id': 'cj6f8vvxb0t552wqmnayyx5w2', 'name': 'points-872899cb2', 'complete': False, 'error': None, 'created': '2017-08-16T16:42:09.125Z', 'modified': '2017-08-16T16:42:09.125Z', 'tileset': 'bravecow.points-872899cb2', 'owner': 'bravecow', 'progress': 0}
```

Using UUID is suggested here: https://github.com/mapbox/mapbox-sdk-py/blob/master/docs/uploads.md#uploads

**Comment by sgillies** [comment]
Ah, we might have an poorly documented limit on name length or a change upstream. I will check and report back.

**Comment by rmutalik** [comment]
Any update on the name length limit? Or an upstream change?

**Comment by perrygeo** [comment]
We've recently updated the API docs to reflect the [naming limits](https://www.mapbox.com/api-documentation/#create-an-upload):

* `tileset` should be `{username}.{nameoftileset}` where username and nameoftileset are limited to a max of 32 characters.
* `name` (the human readable name for the tileset that appears in Studio) is limited to 64 characters.

We'll update the mapbox-sdk-py validation code shortly.

**Comment by perrygeo** [comment]
TODO

* [ ] remove the uuid suggestion from https://github.com/mapbox/mapbox-sdk-py/blob/master/docs/uploads.md#uploads
* [ ] update https://github.com/mapbox/mapbox-sdk-py/blob/e9b49ad4ca58f429986a44aa80fc65874f3ade2b/mapbox/services/uploads.py#L51-L59 with the tileset naming rules above.
