### ISSUE TITLE
Uploader for csv file don't work 

### ISSUE THREAD

**Issue by spatialhast** [mapbox/mapbox-sdk-py#209]
I use pyton Uploader for importing csv file into Mapbox Tileset.
Example python script:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
from mapbox import Uploader

os.environ["MAPBOX_ACCESS_TOKEN"] = "MAPBOX_ACCESS_TOKEN"
tileset = 'USER.TILESET'

base_dir = os.path.realpath(os.path.dirname(__file__))
csv_file = os.path.join(base_dir, "test_csv_file.csv")

print 'start uploading'
	
service = Uploader()
with open(csv_file, 'r') as src:
	upload_resp = service.upload(src, tileset)

print 'uploading completed'	
```

When I import CSV file I receive this error:
![image](https://user-images.githubusercontent.com/3269617/31743168-ca4957c6-b462-11e7-9599-2796a484bca2.png)

When I convert CSV file into GeoJSON and then import this GeoJSON file into Mapbox Tileset - import completed succesfully.

Python 2.7.5
CSV file:  [test_csv_file.zip](https://github.com/mapbox/mapbox-sdk-py/files/1396393/test_csv_file.zip)
Script: 
[csv_import.zip](https://github.com/mapbox/mapbox-sdk-py/files/1396398/csv_import.zip)

**Comment by sgillies** [comment]
@spatialhast thanks for the report ! To be clear, when you write 

> convert CSV file into GeoJSON and then import this GeoJSON file into Mapbox

do you mean that you uploaded the GeoJSON with the SDK or uploaded via the Studio web app?

**Comment by spatialhast** [comment]
when I upload CSV or GeoJSON file via The Mapbox Studio web app - all done successfully.
When I upload CSV file via mapbox-sdk-py - I receive the error as on image above. But GeoJSON file via mapbox-sdk-py I successfully upload.

**Comment by sgillies** [comment]
I was able to upload your CSV file using the Mapbox CLI program and found it in Studio.

```
$ MAPBOX_ACCESS_TOKEN="TOKEN" mapbox upload sgillies.testing_csv test_csv_file.csv
Uploading data source  [####################################]  100%
{"id":"cj90nf2ks2xrp2rmrf28upqld","name":"testing_csv","complete":false,"error":null,"created":"2017-10-21T01:31:33.286Z","modified":"2017-10-21T01:31:33.286Z","tileset":"sgillies.testing_csv","owner":"sgillies","progress":0}
```

If a GeoJSON file worked with mapbox-sdk-py, I think your problem with the CSV has to be another problem. The Python package doesn't treat files differently.

Here's how the CLI performs uploads:

https://github.com/mapbox/mapbox-cli-py/blob/master/mapboxcli/scripts/uploads.py#L70-L71

It's not very different from what you do.

**Comment by spatialhast** [comment]
@sgillies thanks for the provided solution (Node.js uploader) it works - I was able to upload CSV file into Mapbox Studio.
Can you please test python script https://github.com/mapbox/mapbox-sdk-py/files/1396398/csv_import.zip for uploading csv file into Mapbox Studio

**Comment by sgillies** [comment]
@spatialhast please note that I did not provide the Node.js uploader as a solution – mapboxcli is written in Python.

I ran your script and found the problem: the Python boto3 module that we use requires file objects to be opened in binary mode (see https://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.upload_fileobj). This requirement is documented at 

https://github.com/mapbox/mapbox-sdk-py/blob/master/mapbox/services/uploads.py#L249-L250

So, open the CSV with mode 'rb' instead of 'r', and it works.
