### ISSUE TITLE
Response Code 422

### ISSUE THREAD

**Issue by kunalsharma** [mapbox/mapbox-sdk-py#211]
Hi 
After calling 
NavigationLauncher.startNavigation(RouteDetailActivity.this, route,
                                null, true);
i am getting below response. 

Response{protocol=http/1.1, code=422, message=Unknown, url=https://api.mapbox.com/directions/v5/mapbox/driving-traffic/33.360355,-111.801682;-96.914228,32.873916?access_token=pk.eyJ1Ijoic2hhcm1ha3VuYWwxIiwiYSI6ImNqOTZ4azY4aDAweHUycW4zNXZkNWhpZHQifQ.RH-FtCmp02-90Jqw-jxIHQ&geometries=polyline6&overview=full&steps=true&continue_straight=true&annotations=congestion&roundabout_exits=true&voice_instructions=true}

**Comment by perrygeo** [comment]
> `NavigationLauncher.startNavigation`

This doesn't look like a method from the Python SDK. Perhaps you're looking for the Android SDK? https://www.mapbox.com/help/android-navigation-sdk/

Support for directions v5 in the python SDK is not yet released, still a work in progress (see #203).
