### ISSUE TITLE
Add Maps API

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mapbox-sdk-py#228]
It seems like we provide a service for the Static API but not for the Maps API. The main difference is the Maps API allows us to request specific [slippy map tiles](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames) whereas the Static API takes coordinates.

https://www.mapbox.com/api-documentation/#maps

For example for webp high-resolution imagery for tile `(z, x, y)` `(18, 69108, 105092)`:

    https://api.mapbox.com/v4/mapbox.satellite/18/69108/105092@2x.webp?access_token=TOKEN

What's your take on exposing this as a service? cc @perrygeo @sgillies

**Comment by sgillies** [comment]
This is done, thanks to @critical-path . Some work needs to be done in the mapboxcli project before we can release this.

**Comment by perrygeo** [comment]
closed in #235
