### ISSUE TITLE
Directions v4 response returned when using pip install

### ISSUE THREAD

**Issue by coxchapman** [mapbox/mapbox-sdk-py#229]
Heard from a customer today that the Python SDK returns `directions/v4` when used with `pip install mapbox.` @sgillies I think we spoke about updating this a few months ago and I see some changes for v5 committed -- any idea what might be happening here?

**Comment by sgillies** [comment]
@coxchapman the changes are in master but we haven't released yet. I don't see a good reason why we can't get one out soon.
