### ISSUE TITLE
Conventional unix style names for environment variables

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-sdk-py#24]
Environment variables are part of the API and I prefer the good old unix style `MAPBOX_ACCESS_TOKEN` to `MapboxAccessToken`. I don't see any conflicts.

/cc @sbma44 @tmcw @willwhite

**Comment by willwhite** [comment]
I know we are using `MapboxAccessToken` in other libraries. We should be consistent across projects so  you only need to set this once to use any language.

**Comment by sbma44** [comment]
Yeah, this has been standardized in a lot of other places. We should keep it as `MapboxAccessToken`.

**Comment by sgillies** [comment]
From @rclark I learned that `MapboxAccessToken` has its origins in CloudFormation templating. This kinda feels like server side concerns leaking into the client side, but I agree that a shared env var across SDKs is a good thing.
