### ISSUE TITLE
"coodinates" typo

### ISSUE THREAD

**Issue by RomainSF** [mapbox/mapbox-sdk-py#243]
How is this going to be fixed?
My guess is that a lot of people are using the typo in production because mapbox has one, so what's the plan to fix this?

**Comment by sgillies** [comment]
@RomainSF thanks for pointing this out! This GeoJSON output doesn't conform to RFC 7946 and can't be used in any other applications. We're going to fix it by replacing the "coodinates" member with the correct "coordinates" member and won't maintain backwards compatibility.
