### ISSUE TITLE
Mapbox fails to render the points if the input DataFrame start row index is not zero

### ISSUE THREAD

**Issue by bshahbazi** [mapbox/mapbox-sdk-py#254]
Hi,

Mapbox does not work if the DataFrame index does is not zero. It produces an incorrect json output with extra comma at the very first of the json file. An easy fix for it right now is to reset_index of the input DataFrame. The source of issue is at: 

file: mapboxgl-jupyter/mapboxgl/utils.py -> function: df_to_geojson -> line: 49

**Comment by sgillies** [comment]
@bshahbazi I'm sorry, but you've come to the wrong tracker for this issue. Instead, you need to submit something at https://github.com/mapbox/mapboxgl-jupyter/issues.
