### ISSUE TITLE
The coordinate order should be inverted

### ISSUE THREAD

**Issue by Taxuspt** [mapbox/mapbox-sdk-py#262]
https://github.com/mapbox/mapbox-sdk-py/blob/4f97aeef7303d1ca78e734e9e6df44bc15bdad74/mapbox/services/directions.py#L263

`polyline.decode` returns a list of (latitude, longitude) pairs, however the geojson format uses (longitude, latitude).

Thus calling `service.directions()` without explicitly set `geometries` to `geojson` will return a wrongly formatted `geojson`.

**Comment by sgillies** [comment]
Also noted in #250, which was closed before I saw it. Thanks for the report, @Taxuspt !
