### ISSUE TITLE
Python usage strawman

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-sdk-py#3]
What's the #1 Python library for spatial features? [Fiona](https://github.com/Toblerity/Fiona) :smile:, so this API client should aim to fit that well. I'm going to stand up a usage example for us to knock around, starting with vector data since I'm familiar with that part of the API and have done some vector library design. Geocoding and other API client modules will be a bit different but the design style could be similar to this one.

I'm really into the built in Python types and protocols (free documentation! free interoperability!) and less into writing new ones. I'd like to see how far we can go without exposing users to new interfaces.

## Feature data

A feature object is basically deserialized GeoJSON. It could have other methods, but at the core it's this.

```python
{'id': 'lolwut', 'type': 'Feature', ...}
```

## Feature datasets

A Mapbox dataset is among other things a Python [mapping](https://docs.python.org/2/library/stdtypes.html#mapping-types-dict). There are already classes like this in the Python universe (Zope and other B-tree implementations).

You get a dataset object by calling `mapbox.dataset()` with a dataset identifier and auth parameters. 

## Uploading features to Mapbox

Adding new features or updating existing features is done by calling its [update()](https://docs.python.org/2/library/stdtypes.html#dict.update) method.

```python
import fiona
import mapbox

with mapbox.dataset(...) as dst, fiona.open('example.shp') as src:
    dst.update((ftr['id'], ftr) for ftr in src)
```

## Fetching a feature from Mapbox

Fetching a feature is done with everyday indexing syntax.

```python
with mapbox.dataset(...) as dst:
    ftr = dst['lolwut']
    # ftr: {'id': 'lolwut', 'type': 'Feature', ...}
```

## Deleting a feature from Mapbox

As with a mapping.

```python
with mapbox.dataset(...) as dst:
    del dst['lolwut']
```

**Comment by sgillies** [comment]
@planemad @jacquestardie if you've got :eyes: to spare, would love a scan of the above and comments on whether this API style feels good to you.

**Comment by planemad** [comment]
@sgillies looks pretty straightforward to me, although i'll admit i'm a fairly novice coder :monkey:

**Comment by jacquestardie** [comment]
I like this:

> I'm really into the built in Python types and protocols (free documentation! free interoperability!) and less into writing new ones. I'd like to see how far we can go without exposing users to new interfaces.

Agree with @planemad in that this looks good. Nothing stands out as being awkward.

Personally, I find that what you have described here more attractive than #3. :shrug:

**Comment by sgillies** [comment]
@jacquestardie me, too, but this one is pretty fancy and #3 helps it along. I'm going to close this for now and recommend we go ahead in the direction of #3.
