### ISSUE TITLE
Support HTTP-centric and Geojson returns

### ISSUE THREAD

**Issue by perrygeo** [mapbox/mapbox-sdk-py#38]
We need a pattern for the sdk-py so we have methods that 

* return raw responses (i.e don't hide the network)
* return custom geojson or other appropriate data structure parsed from the response (i.e. principle of least surprise, geojson in -> geojson out)

How do we do that? Possibilities...

1. Have paired methods with some naming convention
    - `route` and `route_geojson` or
    - `_route` and `route`
2. return type as a keyword arg (`return_geojson=True`)
3. man in the middle "attack" to massage the API response
4. generic functions or methods that accept the response and do stuff to it
5. ???

**Comment by perrygeo** [comment]
Suggested by @sgillies: 
Add a `geojson` method to the response object. 

This is nice and clean. Doesn't hide the network but also provides a direct method to get custom data structures. I've never seen this pattern before but it seems like a solid design for any python HTTP wrapper.

**Question**: should the `geojson` delay evaluation then evaluate the function on every call or should the geojson data be evaluated early and only once. For example:

```
        # Opt 1: delay and eval on every call to resp.geojson()
        def geojson():
            return self._geojson(resp.json())

        # Opt 2: eval early and only once
        gjmapping = self._geojson(resp.json())
        def geojson():
            return gjmapping
```

**Comment by perrygeo** [comment]
Question: if the service json response is *already* a valid GeoJSON FeatureCollection (as appears to be the case with the geocoder) do we need an additional `geojson()` method? On one hand it's nice for consistency, on the other hand it's rather useless.

**Comment by sgillies** [comment]
@perrygeo let's make it lazy, like requests does: https://github.com/kennethreitz/requests/blob/1dff6c9153448213cd5ed957409de5c809447eba/requests/models.py#L782.

I'm in favor of providing a `geojson()` method even if it just returns `self.json()`. A uniform interface for our SDK responses is a good feature.
