### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-sdk-py#4]
Testing against an API is not the way to go: it's slow, annoys devops, and you can't test offline. A talk I saw at PyCon (ref forthcoming) recommended https://github.com/getsentry/responses for mocking Requests, the library we're going to use to make actual requests.

The mock responses are well explained in the project README; the gist of it is that you create mock response objects with JSON bodies, status codes, headers, etc and register them to a URL and a HTTP method.

**Comment by dnomadb** [comment]
@sgillies yeah, I started hacking on a simple `requests` mimic for this, but responses looks great.

**Comment by tmcw** [comment]
Fwiw we're actually testing against the api in js-land via @yhahn's wisdom - it feels so wrong but works so right in terms of testing real changes in the API

**Comment by sgillies** [comment]
We've got a few tests for both the module and the cli plus Travis and Coveralls config.
