### ISSUE TITLE
Test AWS S3 interaction

### ISSUE THREAD

**Issue by perrygeo** [mapbox/mapbox-sdk-py#51]
The upload API touches AWS S3 services. We should use mocks to unit test this interaction. Initial attempts with moto were not successful due to [this error](https://github.com/spulec/moto/issues/440)

**Comment by sgillies** [comment]
Suggestion from upstream is that pinning `httpretty==0.8.0` should help.

**Comment by sgillies** [comment]
@perrygeo I'm going to pass on moto and try using py.test to [monkeypatch](https://pytest.org/latest/monkeypatch.html) `boto3.session` in our test.

**Comment by sgillies** [comment]
Circling back to this...

@perrygeo the only thing we absolutely need right now for `Uploader` class unit testing is to be able to replace the `Session` object at https://github.com/mapbox/mapbox-sdk-py/blob/master/mapbox/services/uploads.py#L51 with a test double when testing. One classic way to do this is to add a `session_class` keyword argument to `stage()` and pass in our test double class from a test function.

How about we try that for now and defer more general mocking of S3/AWS?

**Comment by perrygeo** [comment]
that sounds good for testing `stage()` itself. 

That only leaves `upload()` which calls `stage`. But a) that gets hit with our doctests and b) it's only two lines, each of which calls a tested function.
