### ISSUE TITLE
Rename Directions.route() to directions()

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-sdk-py#60]
The JS SDK has [`getDirections()`](https://github.com/mapbox/mapbox-sdk-js/blob/master/lib/services/directions.js#L64) but that's not great for Python. How about `directions()` instead of `route()` @perrygeo?

**Comment by perrygeo** [comment]
I think `route` was an attempt to avoid `Directions().directions(..)` repetition. 

What about `get_directions` for consistency? I'm fine with either one.

**Comment by sgillies** [comment]
"get" methods in Python other than `__get__()` and `__getitem__()` rub me the wrong way. The "get" is implied in a method that returns.
