### ISSUE TITLE
Problem with polyline module dependencies

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-sdk-py#74]
@perrygeo I've traced our issues with failing tests on Travis to the `polyline` module requiring exactly one version of `six`. As shown by `pipdeptree`:

```polyline==1.1 -> six [required: ==1.8.0, installed: 1.8.0]```

Everybody would be better off if the requirement were `six>=1.8.0`. I'm going to pursue this upstream and pin the version locally for testing purposes.

**Comment by sgillies** [comment]
@perrygeo PR here: https://github.com/bmcustodio-archive/polyline/pull/2. Polyline looks inactive, so I don't know what to expect. We may need to replace this requirement.

**Comment by perrygeo** [comment]
What about an official fork? It's only about 50 lines of python code and was itself a port of the [`mapbox/polyline` node module](https://github.com/mapbox/polyline).

**Comment by sgillies** [comment]
:+1: to vendorizing it for the next release.

**Comment by perrygeo** [comment]
@tmcw pointed out the the polyline module is alive and well under a new owner: https://github.com/frederickjansen/polyline

@sgillies - it looks like your [PR to fix the six version was merged](https://github.com/frederickjansen/polyline/blob/master/requirements/base.txt) and tests over at [polyline-spectrum](https://github.com/mapbox/polyline-spectrum) show that it's viable.

Let's give it another shot and try to remove the vendorized polyine in the next release.
