### ISSUE TITLE
Testing requests with non-deterministic json.dumps

### ISSUE THREAD

**Issue by perrygeo** [mapbox/mapbox-sdk-py#75]
The static maps API takes urlencoded GeoJSON data. We want to use `responses` to test that our URL is being constructed correctly. But python dictionaries have non-deterministic order so their json.dumps string may not match our mocked URL.

Do we:
* enforce sort order with sort_keys=True? Seems heavy handed to do that just for the sake of testing.
* create multiple mocked URLs for all permutations of the dictionary order? Not very appealing.
* somehow get responses to accept wildcards? Not currently possible it appears.

Any other options? 

cc @sgillies

**Comment by dnomadb** [comment]
I've handled json dumps comparison itself using OrderedDicts, but am not sure how it would pan out in the scenario.

**Comment by perrygeo** [comment]
@dnomadb ordereddict works great for this. And it only requires touching the test code - we don't have to mess with the implementation for the sake of running tests. `collections.OrderedDict` is not in the standard lib in 2.6 but that's easy to work around. Thanks for the suggestion!
