### ISSUE TITLE
Coordinate format for reverse geocoding input

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-sdk-py#8]
I'm always looking for symmetry on the command line, and since a JSON array is the most straightforward output of forward geocoding, it would be great to be able to consume it when reverse geocoding. For example, this (using [jq](http://stedolan.github.io/jq/)) produces JSON:

```bash
$ mapbaux geocode "Bodega Bay, CA" --access-token MY_TOKEN | \
>  jq '.features[0].center' -c
[-123.0481,38.3332]
```

And the round trip could be

```bash
$ mapbaux geocode "Bodega Bay, CA" --access-token MY_TOKEN | \
> jq '.features[0].center' -c | \
> mapbaux geocode --rev --access-token MY_TOKEN
```

There's also precedent in rio-sample for JSON formatted coordinate pairs `[x, y]` or `[long, lat]`

  https://github.com/mapbox/rasterio/blob/master/docs/cli.rst#sample

but it seems like it would be relatively easy to also accept `x y` or `x, y`. There's a pattern that could be expressed as a simple regex.

/cc @dnomadb @sbma44

**Comment by sbma44** [comment]
Yeah, my initial rebelliousness to this idea has melted away. :+1: to consistency and JSONorousness
