### ISSUE TITLE
Create a test user

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-sdk-py#82]
A Mapbox test user specifically for this module's tests.

**Comment by perrygeo** [comment]
For the docstests (branch `moar-docs`), the only blocker now is that the user must have upload scope, https://travis-ci.org/mapbox/mapbox-sdk-py/jobs/95191581#L250

**Comment by sgillies** [comment]
The token had upload scope, and now I've turned on the necessary feature flags for the user.
