### ISSUE TITLE
Feature properties in geocoding response

### ISSUE THREAD

**Issue by perrygeo** [mapbox/mapbox-sdk-py#93]
Here's how feature geojson objects are currently organized in the geocoding API response:
```
$ mapbox geocoding "portland, or" | jq .features[0]
```
```json
{
  "id": "place.39347",
  "type": "Feature",
  "text": "Portland",
  "place_name": "Portland, Oregon, United States",
  "relevance": 0.998,
  "properties": {},
  "bbox": [
    -122.9292140099711,
    45.37948199034149,
    -122.44106199104115,
    45.858097009742835
  ],
  "center": [
    -122.6742,
    45.5202
  ],
  "geometry": {
    "type": "Point",
    "coordinates": [
      -122.6742,
      45.5202
    ]
  },
  "context": [
    {
      "id": "postcode.1060401628",
      "text": "97204"
    },
    {
      "id": "region.3470299826",
      "text": "Oregon"
    },
    {
      "id": "country.4150104525",
      "text": "United States",
      "short_code": "us"
    }
  ]
}
```

That's a whole lot of properties that are not in `properties`. Many tools (noticed it with `fio cat`) will drop this "extraneous" info. **Should the SDK normalize this by putting the non-GeoJSON keys into properties**? Maybe an optional keyword argument (and a CLI flag `--use-properties`)?

```json
{
  "id": "place.39347",
  "type": "Feature",
  "properties": {
      "text": "Portland",
      "place_name": "Portland, Oregon, United States",
      "relevance": 0.998,
      "center": [-122.6742, 45.5202],
      "context": [
        {
          "id": "postcode.1060401628",
          "text": "97204"
        },
        {
          "id": "region.3470299826",
          "text": "Oregon"
        },
        {
          "id": "country.4150104525",
          "text": "United States",
          "short_code": "us"
        }
      ]
  },
  "bbox": [
    -122.9292140099711,
    45.37948199034149,
    -122.44106199104115,
    45.858097009742835
  ],
  "geometry": {
    "type": "Point",
    "coordinates": [
      -122.6742,
      45.5202
    ]
  }
}

```

**Comment by sbma44** [comment]
My own preference is to avoid rewriting responses -- I'd hate to complicate support by having SDK users see something different than they get from `curl`. Besides which I _think_ @sgillies' [last GeoJSON IETF update](https://github.com/mapbox/hey/issues/5084) indicated that nonstandard properties are likely to be allowed to sit wherever we stick 'em.

**Comment by perrygeo** [comment]
@sbma44 - I should clarify. The problem isn't adhering to the spec, it's interop with other tools. The GeoJSON from the geocoding API is 100% valid, a point which doesn't change but will be clarified in the updated GeoJSON spec. But many applications that work with GeoJSON will drop these, meaning that the user looses valuable info by choosing to use other tools. 

For example, opening the output of `mapbox geocoding` in QGIS doesn't show the place names or relevance scores as attributes. I could see the casual user run the command, open in their favorite app and when things don't look right, blaming this cli rather than their app. 

The suggested change would be optional and nothing more than a pragmatic way of dealing with the limitations of other tools. Maybe it's better as an external script? Or just documentation?

**Comment by perrygeo** [comment]
Thinking about this further, I think this task would be better suited to an external tool, maybe a `stuff-everything-in-properties` script that would be more generic and reusable.

**Comment by sgillies** [comment]
@perrygeo fio-cat is intended for non-GeoJSON datasets and only incidentally works on GeoJSON. The better tool for making a sequence of features from a GeoJSON feature collection with extensions is fio-distrib – which does currently discard feature collection properties (like query and attribution).
