### ISSUE TITLE
Provide ids for anonymous features

### ISSUE THREAD

**Issue by sgillies** [mapbox/mapbox-sdk-py#95]
As mentioned in #80. If features are completely anonymous (no id at all) we could give them a uuid. If they have an id `number`, we'll need to either 1) relax the API server's string-only constraint, or 2) migrate the numeric id to a string and come up with a standardizable way to keep the original.

**Comment by perrygeo** [comment]
Maybe slightly off topic but I could see the need for a whole set generic functions to massage the non-geo parts of geojson features. Things like

* add uuids
* stringify ids
* move all "foreign" members into `properties`
* flatten nested `properties` members to make it more tabular GIS friendly

All of these fall under the banner of "you've got valid geojson but you need to tweak it a bit for interoperability with some other tool/service"

Seems like it would be a good fit for a separate lib + CLI. Maybe a fio plugin?

**Comment by sgillies** [comment]
@perrygeo yep, let's keep our SDK light and offload this responsibility.
